### ISSUE TITLE
VMCS Change Request - Enable an accounting check-and-balance

### ISSUE THREAD

**Issue by kennyss76** [kennyss76/VMCS#1]
Enable an accounting check-and-balance that insures that what's reported as collected by the machine is in fact what has been collected by the Maintainer. 

In a recent enhancement (last of the eight done recently), each time "Press to Collect Cash" is pressed, a record that contains the amount collected and the logged in Maintainer's id is captured and recorded in a central database. 

It was later uncovered, however, that what has been recorded by the system often does not always tally with what the Maintainer submits as collected. The maintainer often complains that it is frustrating and time-consuming to manually calculate these amounts; some have given up calculating and others insist that the system displays erroneous amounts than what's physically collected. 

An enhancement is identified to address this problem and especially to aid the Maintainer. The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in "Show Total Cash Held" and "Press to collect Cash" when pressed, thus leaving no room for dispute over system errors.

Note: Refer to ChangeRequest_Ticket_1_Enhancement_v1.0.docx.

**Comment by chenlingreen** [comment]
4 MD for this enhancement.  Yang Min, pls note the effort

**Comment by chenlingreen** [comment]
Change is done. QA to review and confirm

**Comment by andyafter** [comment]
Hi Kennyss,

I'm a little afraid to ask but considering it's about deadline for this CA.

What should an analyst do in this CA?

Thanks!

- An

2015-09-20 20:45 GMT+08:00 kennyss76 <notifications@github.com>:

> Enable an accounting check-and-balance that insures that what's reported
> as collected by the machine is in fact what has been collected by the
> Maintainer.
>
> In a recent enhancement (last of the eight done recently), each time
> "Press to Collect Cash" is pressed, a record that contains the amount
> collected and the logged in Maintainer's id is captured and recorded in a
> central database.
>
> It was later uncovered, however, that what has been recorded by the system
> often does not always tally with what the Maintainer submits as collected.
> The maintainer often complains that it is frustrating and time-consuming to
> manually calculate these amounts; some have given up calculating and others
> insist that the system displays erroneous amounts than what's physically
> collected.
>
> An enhancement is identified to address this problem and especially to aid
> the Maintainer. The system is required to provide an at-a-glance display of
> the cash amount available, by denomination, for collection by the
> Maintainer. This will enable the Maintainer to readily tally the total cash
> collected and the total number of coins by denomination displayed in "Show
> Total Cash Held" and "Press to collect Cash" when pressed, thus leaving no
> room for dispute over system errors.
>
> Note: Refer to ChangeRequest_Ticket_1_Enhancement_v1.0.docx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennyss76/VMCS/issues/1>.
>



-- 
An Pan
Room 120, No. 2
School of Software, Dalian University of Technology
Road No. 8, Development Zone, Dalian 116621
Liaoning, CHINA

**Comment by liuhebian** [comment]
QA: while I am testing this enhancement, I found the Maintenance Panel -> "Show Total Cash Held" total coin value is not readable, please enlarge the width. 

QA: while I am reviewing the design model report, I found the Revision History and Issue Date (in page header) are incomplete. Please update them.

QA: while I am reviewing the design model report, I found we didn't update Static Structure of Maintenance Panel diagram with the new objects : Total Coin Label, CoinLabelItem, CoinLabelItemDisplay. Please update them.

**Comment by liuhebian** [comment]
QA: while I am reviewing the design model report, I found the Revision History and Issue Date (in page header) are incomplete. Please update them.

**Comment by chenlingreen** [comment]
I have updated Design Model Report with History and Issue date into Trunk

**Comment by mianbaogit** [comment]
fix bug and checkin the source

**Comment by chenlingreen** [comment]
Fixed the issues. QM pls verify

**Comment by liuhebian** [comment]
I have reviewed the fixes. Savy, pls verify.

**Comment by savygandhi** [comment]
I have reviewed the Enhancement and tested also. I herby accept to the enhancement. Please initiate further for the final user signup.

**Comment by savygandhi** [comment]
I have reviewed the Enhancement and tested also. I herby accept to the enhancement. Please initiate further for the final user signup.

**Comment by liuhebian** [comment]
Tks! Savy. Hi Thiyagu, user has verified.

**Comment by thiyagarajanp** [comment]
Created the Patch 1.0.9 to include the changes in the next Production release. Kenny, please review and approve.

**Comment by kennyss76** [comment]
Enhancement completed and approved Release Tag R1.0.9.
