### ISSUE TITLE
VMCS Change Request - Reset the Values to null

### ISSUE THREAD

**Issue by kennyss76** [kennyss76/VMCS#2]
Reset the Values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”. The Simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and held collected, persists in display. This sometimes causes confusion to Maintainer.  

Note: Refer to ChangeRequest_Ticket_2_Defect_v1.0.docx.

**Comment by chenlingreen** [comment]
Huang Cun, the effort to do this bug fix is 2 MD

**Comment by huangc8606** [comment]
@chenlingreen changes are done, please merge and verify

**Comment by chenlingreen** [comment]
Change is done. QA to review and confirm

**Comment by liuhebian** [comment]
QA: The issue is fixed and design model report is updated. Savy, please verify.

**Comment by savygandhi** [comment]
I have reviewed the Defect correction and tested also. I herby accept to the defect correction. Please initiate further for the final user signup.

**Comment by liuhebian** [comment]
Tks! Savy. Hi Thiyagu, user has verified.

**Comment by thiyagarajanp** [comment]
Created the Patch 1.0.9 to include the changes for the Production Release. Kenny, Please review and approvel

**Comment by kennyss76** [comment]
Defect rectified and approved Release Tag R1.0.9.
